[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
feature-creep-types.workspace = true

leptos.workspace = true
leptos-use.workspace = true
serde_json.workspace = true
leptos_dom.workspace = true
rand.workspace = true
getrandom = { workspace = true, features = ["wasm_js"] }
wasm-bindgen.workspace = true
