[package]
name = "feature-creep"
version = "0.1.0"
edition = "2021"

[dependencies]
bhbadge2024.workspace = true
feature-creep-types.workspace = true

esp-hal-embassy.workspace = true
esp-hal.workspace = true
embassy-executor.workspace = true
embassy-time.workspace = true
esp-println.workspace = true
esp-wifi.workspace = true
static_cell.workspace = true
embassy-net.workspace = true
picoserve.workspace = true
serde-json-core.workspace = true
embassy-sync.workspace = true
embassy-futures.workspace = true
