[package]
name = "feature-creep"
version = "0.1.0"
edition = "2021"

[dependencies]
feature-creep-types.workspace = true

accelerometer.workspace = true
cast.workspace = true
embassy-executor.workspace = true
embassy-futures.workspace = true
embassy-net.workspace = true
embassy-sync.workspace = true
embassy-time.workspace = true
esp-alloc.workspace = true
esp-backtrace.workspace = true
esp-hal.workspace = true
esp-hal-embassy.workspace = true
esp-println.workspace = true
esp-wifi.workspace = true
micromath.workspace = true
num-derive.workspace = true
num-traits.workspace = true
picoserve.workspace = true
serde-json-core.workspace = true
smoltcp.workspace = true
static_cell.workspace = true
