[workspace]
members = ["crates/*"]
exclude = ["crates/frontend"]
resolver = "2"

[workspace.dependencies]
feature-creep.path = "crates/feature-creep"
feature-creep-types.path = "crates/feature-creep-types"
frontend.path = "crates/frontend"

accelerometer = "0.12.0"
cast = "0.3.0"
embassy-executor = { version = "0.7.0", features = ["task-arena-size-131072"] }
embassy-futures = "0.1.1"
embassy-net = { version = "0.7.0", features = [
    "proto-ipv4",
    "dhcpv4",
    "tcp",
    "dns",
] }
embassy-sync = "0.7.0"
embassy-time = { version = "0.4.0", features = ["generic-queue-8"] }
esp-alloc = "0.8.0"
esp-backtrace = { version = "0.17", features = [
    "esp32c3",
    "exception-handler",
    "panic-handler",
    "println",
] }
esp-hal = { version = "1.0.0-rc.0", features = ["esp32c3", "unstable"] }
esp-hal-embassy = { version = "0.9.0", features = ["esp32c3"] }
esp-println = { version = "0.15.0", features = ["esp32c3", "log-04"] }
esp-wifi = { version = "0.15.0", features = ["esp32c3", "wifi"] }
micromath = "2.1.0"
num-derive = { version = "0.4.2", default-features = false }
num-traits = { version = "0.2.19", default-features = false }
picoserve = { version = "0.16.0", features = ["embassy"] }
serde = { version = "1.0.204", default-features = false, features = ["derive"] }
serde-json-core = "0.5.1"
smoltcp = { version = "0.12.0", default-features = false, features = [
    "socket",
    "async",
    "log",
] }
static_cell = "2.1.0"

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1        # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false
